/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.semestralka;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author namer
 */
public class main extends javax.swing.JFrame {
    
    private Application app;
    
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        this.initApp();
    }
    
    //Start moje metody
    private void initApp() {
        //nastavi zobrazovanie okien na stred obrazovky
        this.setLocationRelativeTo(null); 
        this.jFrameNodeDetails.setLocationRelativeTo(null);
        this.jFrameEdgeDetails.setLocationRelativeTo(null);
        //vytvorenie instancie aplikacie
        this.app = new Application(); 
        this.setTitle(this.app.getMode().toString());
    }
    
    public void openNodeDetailWindow() {
        Uzol node = this.app.getOtvorenyUzol();
        if (node != null) {//pokracujem len ak node ktory mam zobrazit nie je null
            //nacitanie info do okna pre otvoreny uzol
            this.jTextFieldNodeDetailsNazov.setText(node.getNazov());
            this.jTextFieldNodeDetailsKapacita.setText(Integer.toString(node.getKapacita()));
            this.jComboBoxNodeDetailsTypUzla.setSelectedItem(node.getTypUzla());
            //nastavenie viditelnosti daneho okna
            this.jFrameNodeDetails.setVisible(true);
            this.jPanelNodeDetails.setVisible(true);
            //deaktivujem main okno aby sa nedalo klikat tam ale aby bol focus na tom detaile
            this.setEnabled(false);
        }
    }
    
    public void openEdgeDetailWindow() {
        Hrana edge = this.app.getOtvorenaHrana();
        if (edge != null) {//pokracujem len ak edge ktory mam zobrazit nie je null
            //nacitanie info do okna pre otvorenu hranu
            this.jTextFieldEdgeDetailsDlzka.setText(Double.toString(edge.getDlzkaTrasy()));
            this.jCheckBoxEdgeDetailsPovolenieHrany.setSelected(edge.isHranaPovolena());
            //nastavenie viditelnosti daneho okna
            this.jFrameEdgeDetails.setVisible(true);
            this.jPanelEdgeDetails.setVisible(true);
            //deaktivujem main okno aby sa nedalo klikat tam ale aby bol focus na tom detaile
            this.setEnabled(false);
        }
    }
    
    /**
     * Metoda pre zmenu modu aplikacie
     * @param newMode novy mod
     */
    public void changeMode(Mode newMode) {
        this.app.setMode(newMode);
        this.setTitle(newMode.toString());
    }
    //End moje metody

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNodeDetails = new javax.swing.JFrame();
        jPanelNodeDetails = new javax.swing.JPanel();
        jLabelNodeDetailsNazov = new javax.swing.JLabel();
        jTextFieldNodeDetailsNazov = new javax.swing.JTextField();
        jLabelNodeDetailsKapacita = new javax.swing.JLabel();
        jTextFieldNodeDetailsKapacita = new javax.swing.JTextField();
        jLabelNodeDetailsTypUzla = new javax.swing.JLabel();
        jComboBoxNodeDetailsTypUzla = new javax.swing.JComboBox<>();
        jFrameEdgeDetails = new javax.swing.JFrame();
        jPanelEdgeDetails = new javax.swing.JPanel();
        jLabelEdgeDetailsDlzka = new javax.swing.JLabel();
        jTextFieldEdgeDetailsDlzka = new javax.swing.JTextField();
        jLabelEdgeDetailsPovolenieHrany = new javax.swing.JLabel();
        jCheckBoxEdgeDetailsPovolenieHrany = new javax.swing.JCheckBox();
        jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy = new javax.swing.JButton();
        jFileChooserSaveLocation = new javax.swing.JFileChooser();
        jPanelMain = new javax.swing.JPanel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuUzly = new javax.swing.JMenu();
        jMenuItemUzlyPridavanie = new javax.swing.JMenuItem();
        jMenuItemUzlyEditacia = new javax.swing.JMenuItem();
        jMenuItemUzlyMazanie = new javax.swing.JMenuItem();
        jMenuHrany = new javax.swing.JMenu();
        jMenuItemHranyPridavanie = new javax.swing.JMenuItem();
        jMenuItemHranyEditacia = new javax.swing.JMenuItem();
        jMenuItemHranyMazanie = new javax.swing.JMenuItem();
        jMenuSubor = new javax.swing.JMenu();
        jMenuItemSuborNacitanie = new javax.swing.JMenuItem();
        jMenuItemSuborUlozenie = new javax.swing.JMenuItem();

        jFrameNodeDetails.setAlwaysOnTop(true);
        jFrameNodeDetails.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrameNodeDetails.setResizable(false);
        jFrameNodeDetails.setType(java.awt.Window.Type.POPUP);
        jFrameNodeDetails.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameNodeDetailsWindowClosing(evt);
            }
        });

        jLabelNodeDetailsNazov.setText("Nazov");

        jTextFieldNodeDetailsNazov.setMinimumSize(new java.awt.Dimension(200, 22));
        jTextFieldNodeDetailsNazov.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabelNodeDetailsKapacita.setText("Kapacita");

        jTextFieldNodeDetailsKapacita.setMinimumSize(new java.awt.Dimension(200, 22));
        jTextFieldNodeDetailsKapacita.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabelNodeDetailsTypUzla.setText("Typ uzla");

        jComboBoxNodeDetailsTypUzla.setModel(new DefaultComboBoxModel<>(TypUzla.values()));
        jComboBoxNodeDetailsTypUzla.setMinimumSize(new java.awt.Dimension(200, 22));
        jComboBoxNodeDetailsTypUzla.setPreferredSize(new java.awt.Dimension(200, 22));

        javax.swing.GroupLayout jPanelNodeDetailsLayout = new javax.swing.GroupLayout(jPanelNodeDetails);
        jPanelNodeDetails.setLayout(jPanelNodeDetailsLayout);
        jPanelNodeDetailsLayout.setHorizontalGroup(
            jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeDetailsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNodeDetailsKapacita)
                    .addComponent(jLabelNodeDetailsNazov, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNodeDetailsTypUzla, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNodeDetailsNazov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNodeDetailsKapacita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNodeDetailsTypUzla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanelNodeDetailsLayout.setVerticalGroup(
            jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeDetailsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNodeDetailsNazov)
                    .addComponent(jTextFieldNodeDetailsNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNodeDetailsKapacita)
                    .addComponent(jTextFieldNodeDetailsKapacita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNodeDetailsTypUzla)
                    .addComponent(jComboBoxNodeDetailsTypUzla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameNodeDetailsLayout = new javax.swing.GroupLayout(jFrameNodeDetails.getContentPane());
        jFrameNodeDetails.getContentPane().setLayout(jFrameNodeDetailsLayout);
        jFrameNodeDetailsLayout.setHorizontalGroup(
            jFrameNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNodeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameNodeDetailsLayout.setVerticalGroup(
            jFrameNodeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNodeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameEdgeDetails.setAlwaysOnTop(true);
        jFrameEdgeDetails.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrameEdgeDetails.setResizable(false);
        jFrameEdgeDetails.setType(java.awt.Window.Type.POPUP);
        jFrameEdgeDetails.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameEdgeDetailsWindowClosing(evt);
            }
        });

        jLabelEdgeDetailsDlzka.setText("Dlzka trasy");

        jTextFieldEdgeDetailsDlzka.setMinimumSize(new java.awt.Dimension(200, 22));
        jTextFieldEdgeDetailsDlzka.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabelEdgeDetailsPovolenieHrany.setText("Povolenie hrany");

        jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy.setText("Automaticky vypocitat dlzku trasy");
        jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEdgeDetailsLayout = new javax.swing.GroupLayout(jPanelEdgeDetails);
        jPanelEdgeDetails.setLayout(jPanelEdgeDetailsLayout);
        jPanelEdgeDetailsLayout.setHorizontalGroup(
            jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdgeDetailsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEdgeDetailsPovolenieHrany)
                    .addComponent(jLabelEdgeDetailsDlzka, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdgeDetailsLayout.createSequentialGroup()
                        .addComponent(jTextFieldEdgeDetailsDlzka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanelEdgeDetailsLayout.createSequentialGroup()
                        .addComponent(jCheckBoxEdgeDetailsPovolenieHrany)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelEdgeDetailsLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEdgeDetailsLayout.setVerticalGroup(
            jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdgeDetailsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdgeDetailsDlzka)
                    .addComponent(jTextFieldEdgeDetailsDlzka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdgeDetailsPovolenieHrany)
                    .addComponent(jCheckBoxEdgeDetailsPovolenieHrany))
                .addGap(31, 31, 31)
                .addComponent(jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameEdgeDetailsLayout = new javax.swing.GroupLayout(jFrameEdgeDetails.getContentPane());
        jFrameEdgeDetails.getContentPane().setLayout(jFrameEdgeDetailsLayout);
        jFrameEdgeDetailsLayout.setHorizontalGroup(
            jFrameEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEdgeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameEdgeDetailsLayout.setVerticalGroup(
            jFrameEdgeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEdgeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFileChooserSaveLocation.setCurrentDirectory(new java.io.File("C:\\D\\Desktop\\School\\4.Rocnik\\Implementacia_optimalizacnych_algoritmov\\Semestralka\\semestralka\\files"));
        jFileChooserSaveLocation.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooserSaveLocation.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelMain.setAlignmentX(0.0F);
        jPanelMain.setAlignmentY(10.0F);
        jPanelMain.setPreferredSize(new java.awt.Dimension(1000, 777));
        jPanelMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1456, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );

        jMenuUzly.setText("Uzly");

        jMenuItemUzlyPridavanie.setLabel("Pridanie uzlov");
        jMenuItemUzlyPridavanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUzlyPridavanieActionPerformed(evt);
            }
        });
        jMenuUzly.add(jMenuItemUzlyPridavanie);

        jMenuItemUzlyEditacia.setLabel("Editacia Uzlov");
        jMenuItemUzlyEditacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUzlyEditaciaActionPerformed(evt);
            }
        });
        jMenuUzly.add(jMenuItemUzlyEditacia);

        jMenuItemUzlyMazanie.setLabel("Mazanie Uzlov");
        jMenuItemUzlyMazanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUzlyMazanieActionPerformed(evt);
            }
        });
        jMenuUzly.add(jMenuItemUzlyMazanie);

        jMenuBarMain.add(jMenuUzly);

        jMenuHrany.setText("Hrany");

        jMenuItemHranyPridavanie.setText("Pridanie hran");
        jMenuItemHranyPridavanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHranyPridavanieActionPerformed(evt);
            }
        });
        jMenuHrany.add(jMenuItemHranyPridavanie);

        jMenuItemHranyEditacia.setText("Editacia hran");
        jMenuItemHranyEditacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHranyEditaciaActionPerformed(evt);
            }
        });
        jMenuHrany.add(jMenuItemHranyEditacia);

        jMenuItemHranyMazanie.setText("Mazanie hran");
        jMenuItemHranyMazanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHranyMazanieActionPerformed(evt);
            }
        });
        jMenuHrany.add(jMenuItemHranyMazanie);

        jMenuBarMain.add(jMenuHrany);

        jMenuSubor.setText("Subor");

        jMenuItemSuborNacitanie.setText("Nacitanie dat zo suboru");
        jMenuSubor.add(jMenuItemSuborNacitanie);

        jMenuItemSuborUlozenie.setText("Ulozenie dat do suboru");
        jMenuItemSuborUlozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSuborUlozenieActionPerformed(evt);
            }
        });
        jMenuSubor.add(jMenuItemSuborUlozenie);

        jMenuBarMain.add(jMenuSubor);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainMouseClicked
        //mouse on click listener
        int posX=evt.getX();
        int posY=evt.getY();
        
        switch (this.app.mouseClicked(posX, posY, jPanelMain)) {
            case 1:
                repaint();
                this.openNodeDetailWindow(); //zobrazi uzol ktory je v this.app.otvorenyUzol
                break;
            case 2:
                repaint();
                break;
            case 3:
                repaint();
                this.openEdgeDetailWindow();//zobrazi hranu ktora je v this.app.otvorenaHrana
                break;
            default:
                //do nothing
        }       
        
    }//GEN-LAST:event_jPanelMainMouseClicked

    private void jFrameNodeDetailsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameNodeDetailsWindowClosing
        Uzol otvorenyUzol = this.app.getOtvorenyUzol();
        // nastavime hodnoty z obrazovky
        otvorenyUzol.setNazov(this.jTextFieldNodeDetailsNazov.getText());
        try {
            otvorenyUzol.setKapacita(Integer.parseInt(this.jTextFieldNodeDetailsKapacita.getText()));
        } catch (NumberFormatException e) {
            //Do nothing
        }
        otvorenyUzol.setTypUzla((TypUzla)this.jComboBoxNodeDetailsTypUzla.getSelectedItem());
        
        // nastavime otvoreny uzol na null
        this.app.setOtvorenyUzol(null);
        this.setEnabled(true);
    }//GEN-LAST:event_jFrameNodeDetailsWindowClosing

    private void jMenuItemUzlyPridavanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUzlyPridavanieActionPerformed
        this.changeMode(Mode.addNode); //pridavanie uzlov
    }//GEN-LAST:event_jMenuItemUzlyPridavanieActionPerformed

    private void jMenuItemUzlyEditaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUzlyEditaciaActionPerformed
        this.changeMode(Mode.editNode); //editacia uzlov
    }//GEN-LAST:event_jMenuItemUzlyEditaciaActionPerformed

    private void jMenuItemUzlyMazanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUzlyMazanieActionPerformed
        this.changeMode(Mode.removeNode); //mazanie uzlov
    }//GEN-LAST:event_jMenuItemUzlyMazanieActionPerformed

    private void jMenuItemHranyPridavanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHranyPridavanieActionPerformed
        this.changeMode(Mode.addEdge);
    }//GEN-LAST:event_jMenuItemHranyPridavanieActionPerformed

    private void jMenuItemHranyEditaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHranyEditaciaActionPerformed
        this.changeMode(Mode.editEdge);
    }//GEN-LAST:event_jMenuItemHranyEditaciaActionPerformed

    private void jMenuItemHranyMazanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHranyMazanieActionPerformed
        this.changeMode(Mode.removeEdge);
    }//GEN-LAST:event_jMenuItemHranyMazanieActionPerformed

    private void jFrameEdgeDetailsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameEdgeDetailsWindowClosing
        Hrana otvorenaHrana = this.app.getOtvorenaHrana();
        // nastavime hodnoty z obrazovky
        try {
            otvorenaHrana.setDlzkaTrasy(Double.parseDouble(this.jTextFieldEdgeDetailsDlzka.getText()));
        } catch (NumberFormatException e) {
            //Do nothing
        }
        otvorenaHrana.setHranaPovolena(this.jCheckBoxEdgeDetailsPovolenieHrany.isSelected());
        
        // nastavime otvorenu hranu na null
        this.app.setOtvorenaHrana(null);
        this.setEnabled(true);
    }//GEN-LAST:event_jFrameEdgeDetailsWindowClosing

    private void jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasyActionPerformed
        Hrana edge = this.app.getOtvorenaHrana();
        edge.autoCalculateLength();
        this.jTextFieldEdgeDetailsDlzka.setText(Double.toString(edge.getDlzkaTrasy()));
    }//GEN-LAST:event_jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasyActionPerformed

    private void jMenuItemSuborUlozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSuborUlozenieActionPerformed
//        if (this.application == null) {
//            JOptionPane.showMessageDialog(this.jPanelSearchProperties, "Aplikácia nie je inicializovaná", "Chyba", JOptionPane.ERROR_MESSAGE);
//        }
//        else {
            this.jFileChooserSaveLocation.showSaveDialog(this);
            try {
                if (this.jFileChooserSaveLocation.getSelectedFile().isDirectory()) {
                    this.app.saveData(this.jFileChooserSaveLocation.getSelectedFile().getPath());
                    JOptionPane.showMessageDialog(this.jPanelMain, "Uloženie dát sa podarilo");
                }
            } catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
//        }

    }//GEN-LAST:event_jMenuItemSuborUlozenieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdgeDetailsAutomatickyVypocetDlzkyTrasy;
    private javax.swing.JCheckBox jCheckBoxEdgeDetailsPovolenieHrany;
    private javax.swing.JComboBox<TypUzla> jComboBoxNodeDetailsTypUzla;
    private javax.swing.JFileChooser jFileChooserSaveLocation;
    private javax.swing.JFrame jFrameEdgeDetails;
    private javax.swing.JFrame jFrameNodeDetails;
    private javax.swing.JLabel jLabelEdgeDetailsDlzka;
    private javax.swing.JLabel jLabelEdgeDetailsPovolenieHrany;
    private javax.swing.JLabel jLabelNodeDetailsKapacita;
    private javax.swing.JLabel jLabelNodeDetailsNazov;
    private javax.swing.JLabel jLabelNodeDetailsTypUzla;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuHrany;
    private javax.swing.JMenuItem jMenuItemHranyEditacia;
    private javax.swing.JMenuItem jMenuItemHranyMazanie;
    private javax.swing.JMenuItem jMenuItemHranyPridavanie;
    private javax.swing.JMenuItem jMenuItemSuborNacitanie;
    private javax.swing.JMenuItem jMenuItemSuborUlozenie;
    private javax.swing.JMenuItem jMenuItemUzlyEditacia;
    private javax.swing.JMenuItem jMenuItemUzlyMazanie;
    private javax.swing.JMenuItem jMenuItemUzlyPridavanie;
    private javax.swing.JMenu jMenuSubor;
    private javax.swing.JMenu jMenuUzly;
    private javax.swing.JPanel jPanelEdgeDetails;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNodeDetails;
    private javax.swing.JTextField jTextFieldEdgeDetailsDlzka;
    private javax.swing.JTextField jTextFieldNodeDetailsKapacita;
    private javax.swing.JTextField jTextFieldNodeDetailsNazov;
    // End of variables declaration//GEN-END:variables
}
